### ISSUE TITLE
[BUG] occasionally unable to send SOL

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1094]
**Describe the bug**
Recently when trying to send SOL, especially `max` amount, different error getting prompted and user is unable to send SOL.

**Expected behavior**
Consistent sending possible

**Screenshots**
![Image](https://github.com/user-attachments/assets/b60412fb-c73c-4534-ba7b-b5db75a3b50f)
![Image](https://github.com/user-attachments/assets/96d2ee31-a538-44d0-8ce4-ebc13bc03b05)
![Image](https://github.com/user-attachments/assets/4993c19f-0adb-4383-a913-6e4449005adc)

 - Version 25

**Additional context**
Often the pairing device also gets "too many RPC calls" error but tx goes through

**Comment by johnnyluo** [comment]
This also should have been fixed by #1098 and #1036

**Comment by realpaaao** [comment]
@johnnyluo @aminsato I am still getting this error on almost all tx when fast signing. It is not possible for me to fast sign

**Comment by realpaaao** [comment]
QA done. But getting sending errors for SPL see #1205
