### ISSUE TITLE
[BUG] Unable to send SOL SPL tokens

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1205]
**Describe the bug**
Not possible to send out SPL tokens and getting` invalid account data for instruction` error

**To Reproduce**
1. Try sending any SPL token
3. See error

**Expected behavior**
Able to send SPL tokens

**Screenshots**
![Image](https://github.com/user-attachments/assets/2be0f36b-d4f2-4e76-b3fc-ecaccc486529)

-on `main` branch

**Additional context**

**Comment by johnnyluo** [comment]
has this one bee fixed in latest version (v1.0.30)?  did you try it?

**Comment by realpaaao** [comment]
@aminsato I am still unable to send SPL tokens on version 32. Please prioritize.

![Image](https://github.com/user-attachments/assets/90e72526-874d-4606-b8bf-1f4e7c678b5e)

**Comment by realpaaao** [comment]
@aminsato I still can't send on `main` branch.

Either blockhash not found - where are we with the durable nonce?

Or getting a valid tx hash on vultisig but is not broadcasted on-chain

**Comment by realpaaao** [comment]
Close for testing
